spring:
  datasource:
    url: jdbc:mysql://tubu-db.cphupoegyqrb.ap-northeast-2.rds.amazonaws.com:3306/tubu?serverTimezone=UTC&characterEncoding=UTF-8
    username: tubu
    password: tubu1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

